### ISSUE TITLE
Error: Property 'then' does not exist on type 'Batch'

### ISSUE THREAD

**Issue by raydvard** [JBooker10/node-iex-cloud#12]
As this document states: [https://github.com/JBooker10/node-iex-cloud#batch-symbols--types](https://github.com/JBooker10/node-iex-cloud#batch-symbols--types)

I am having issues while using `.batch()` and `.then()` together.

The error is:
`Property 'then' does not exist on type 'Batch'`

Please help me with this.

**Comment by JBooker10** [comment]
Hi @raydvard, the `batch` method allows you to chain specific iex data types together and would need to be closed with the `range` method. The below example we see `book()`, `company()` and `sentiment()` are data-types that can be batched together following the range method. You can not return a batch request without chaining the `IEX data-type`and the `range()` on it.  example below:

```javascript
iex
  .symbol("aapl")
  .batch()
  .book()
  .company()
  .sentiment()
  .range()
  .then(res => console.log(res))
  .catch(err => console.log(err));
````
