### ISSUE TITLE
process.env error for publishable?

### ISSUE THREAD

**Issue by Alifar** [JBooker10/node-iex-cloud#17]
Hi there, first of thanks for this great project. I am getting an error when I use the API token in a process.env saying that the token is invalid. When I use that exact same token hard coded it works just fine. Do you have a idea why this is happening? I am running on node v14.5.0

```javascript
const iex = new IEXCloudClient(fetch, {
	sandbox: true,
	publishable: `${process.env.IEX_API_TOKEN}`,
	version: 'stable',
});
```

**Comment by Alifar** [comment]
Also, when I console log the process.env.IEX_API_TOKEN it shows the correct token

**Comment by JBooker10** [comment]
@Alifar, sorry for the delay,  having a hard time reproducing this issue. Have you tried checking to see if there is any white space or empty spaces on your token?
