### ISSUE TITLE
Doc typo?

### ISSUE THREAD

**Issue by ptmdmusique** [JBooker10/node-iex-cloud#24]
Hello, thanks for the project!

I noticed the doc specifies IEX only allows up to 10 symbols for batch request, but I think the official docs says 100? Maybe IEX made an update recently 🤔 
![image](https://user-images.githubusercontent.com/37349324/114439853-4d4cde80-9b7e-11eb-846a-1c275770fd5d.png)

Could you double-check ❓

**Comment by JBooker10** [comment]
I will update the docs thanks for the heads up 👍🏾

**Comment by ptmdmusique** [comment]
Thanks! Closing the issue
