### ISSUE TITLE
Getting historical data for a specific date

### ISSUE THREAD

**Issue by peterdee** [JBooker10/node-iex-cloud#3]
Hi.
I'm trying to get some stock data for a specific date.
The official IEX Cloud documentation suggests the following format:
```
/stock/aapl/chart/date/20190109?chartByDay=true
```

The request for the `chart` data looks like this:
```
return _this.request('chart/' + range + (params
  ? '?' + Object.entries(params).map(param => `${param[0]}=${param[1]}`).join('&')
  : ''));
```
As I understand, it's not possible to load the stock data for a specific date.

Please let me know if I can do a PR that adds this functionality.

**Comment by JBooker10** [comment]
@peterdee Absolutely, thanks for pointing this out. Let me know if you have any additional questions.

**Comment by peterdee** [comment]
@JBooker10 Ok.
I've created a pull request. Let me know if there are any issues with it. If everything's fine, this issue can be closed.

**Comment by JBooker10** [comment]
Everything is good to go. Merged. Thanks!
