### ISSUE TITLE
Batch.shortInterest is invalid

### ISSUE THREAD

**Issue by i3dly** [JBooker10/node-iex-cloud#7]
Hi.

It appears that when I request batch data with `shortInterest` with a single symbol nothing is returned.

`iex.symbol("googl").batch().shortInterest()...`

And when I request batch data with `shortInterest` with multiple symbols via `batchSymbol`, I get an error: `Error: "types" required with a valid value`.

`iex.batchSymbols("googl", "aapl").batch().shortInterest()...`

I don't see this request within IEX-Cloud docs. Maybe it should be omitted from `Batch`?

**Comment by JBooker10** [comment]
Good find. Will remove this in the next release
